import Mathlib.Data.Set.Basic
import Mathlib.Data.SetLike.Basic
import Mathlib.Order.Filter.Basic
import ComputableReal.InfStream

open Filter

/-!
  # InfStream filter interface
-/

universe u v w

namespace InfStream

variable {β : Type u} {α : Type w} [SetLike α β] {τ : Type u} {T : τ → Type v}

/--
  Constructs the filter generated by the sequence of shapes.
-/
def filterFromShapeSeq (s : ℕ → α) : Filter β :=
  Filter.generate (Set.range (fun n ↦ (s n : Set β)))

/--
  Generates a Filter from the stream.
  (Valid when α has a SetLike instance interpreted as sets of β)
-/
def toFilter (s : InfStream τ T α) : Filter β :=
  filterFromShapeSeq (s.seq ·)

lemma toFilter_ofFn_eq_filterFromShapeSeq [Inhabited τ] [Inhabited (T default)] (s : ℕ → α) :
    (InfStream.ofFn (τ:=τ) (T:=T) s).toFilter = filterFromShapeSeq s := by
  rw [toFilter]
  simp [InfStream.seq_ofFn]

end InfStream
